name: slowtokstream
description: Stream to slowtok

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  camera: ^0.7.0+2
  path_provider: ^1.6.7
  path: ^1.7.0
  http: ^0.12.0+4
  compressimage: ^0.1.1
  shared_preferences: ^0.5.12+4
  google_sign_in: any
  provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

